// src/components/PortfolioCard.jsx
import Arrow from "../assets/img/arrow.svg";
import { motion } from "framer-motion";

const PortfolioCard = ({ project, variants }) => {
    return (
        <motion.div
            className="bg-white bg-opacity-5 rounded-lg p-6 sm:p-10 flex flex-col md:flex-row items-center gap-8 md:gap-12 w-full shadow-xl border border-white border-opacity-5"
            variants={variants}
        >
            <div className="flex justify-center items-center w-full md:w-1/2">
                <img
                    src={`https:${project?.fields?.image?.fields?.file?.url}`}
                    alt={`Image for ${project.fields.title}`}
                    className="max-w-full max-h-80 lg:max-w-4/5"
                    loading="lazy"
                />
            </div>

            <div className="flex flex-col gap-4 items-center md:items-start w-full md:w-1/2">
                <h2 className="text-2xl font-semibold text-center md:text-left">
                    {project.fields.title}
                </h2>

                <div className="flex gap-2 flex-wrap justify-center md:justify-start w-full">
                    {project.fields.tags.map((tag) => (
                        <span
                            key={tag.fields.name}
                            className="flex items-center gap-1 bg-white bg-opacity-10 py-1 px-2.5 rounded-full text-xs border border-white border-opacity-10"
                        >
                            {tag.fields.icon && (
                                <img
                                    src={`https:${tag?.fields?.icon?.fields?.file?.url}`}
                                    alt={tag.fields.name}
                                    width="16"
                                    height="16"
                                />
                            )}
                            {tag.fields.name}
                        </span>
                    ))}
                </div>

                <p className="text-center md:text-left">
                    {project.fields.description}
                </p>

                {project.fields.githubLink && (
                    <a
                        href={project.fields.githubLink}
                        target="_blank"
                        className="button flex gap-2"
                        aria-label={`Show ${project.fields.title} on GitHub`}
                    >
                        Show on GitHub <img src={Arrow} alt="Arrow icon" />
                    </a>
                )}
            </div>
        </motion.div>
    );
};

export default PortfolioCard;

// src/components/PortfolioCard.vue
<script setup>
defineProps({
    data: {
        type: Object,
        required: true,
    },
});
</script>

<template>
    <div class="p-6 sm:p-8 flex flex-col sm:flex-row gap-8 sm:gap-12 bg-zinc-700/25 rounded-4xl">
        <div class="flex justify-center items-center sm:w-1/2">
            <img
                :src="data.image"
                :alt="'Screenshot of ' + data.title"
                class="max-w-full max-h80"
                loading="lazy"
            />
        </div>
        <div class="flex flex-col gap-4 sm:w-1/2 relative">
            <h2 class="text-2xl font-medium text-center sm:text-left truncate">{{ data.title }}</h2>
            <div class="flex justify-center sm:justify-start gap-2 flex-wrap">
                <div
                    v-for="tag in data.tags"
                    class="text-sm bg-white/10 px-3 py-1 rounded-full flex items-center gap-1.5 text-neutral-200"
                >
                    <img
                        :src="tag.fields.icon.fields.file.url"
                        :alt="tag.fields.name"
                        width="14"
                        height="14"
                    />
                    <span>{{ tag.fields.name }}</span>
                </div>
            </div>

            <p class="mb-16 text-center sm:text-left">{{ data.description }}</p>

            <a
                v-if="data.githubURL"
                :href="data.githubURL"
                class="button absolute bottom-0 w-full"
                target="_blank"
            >
                View on <Icon icon="mdi:github" width="24" height="24" />
            </a>
        </div>
    </div>
</template>
